// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIbs3DG4aEIBi_Y-QlRblSHpClO2GOgKc',
    appId: '1:539148257805:web:e1f103304959938fdb6344',
    messagingSenderId: '539148257805',
    projectId: 'auth-6a157',
    authDomain: 'auth-6a157.firebaseapp.com',
    storageBucket: 'auth-6a157.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2hL9WQqzfmaQ_cQ6q4DURjP_ElqLL8c',
    appId: '1:539148257805:android:368eeba3a3be70cedb6344',
    messagingSenderId: '539148257805',
    projectId: 'auth-6a157',
    storageBucket: 'auth-6a157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI0dCS1ky9l8d44F4rGHJFB0ikifkhln4',
    appId: '1:539148257805:ios:5b8bf356445fa14adb6344',
    messagingSenderId: '539148257805',
    projectId: 'auth-6a157',
    storageBucket: 'auth-6a157.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI0dCS1ky9l8d44F4rGHJFB0ikifkhln4',
    appId: '1:539148257805:ios:5b8bf356445fa14adb6344',
    messagingSenderId: '539148257805',
    projectId: 'auth-6a157',
    storageBucket: 'auth-6a157.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIbs3DG4aEIBi_Y-QlRblSHpClO2GOgKc',
    appId: '1:539148257805:web:ee9b5cc61662e392db6344',
    messagingSenderId: '539148257805',
    projectId: 'auth-6a157',
    authDomain: 'auth-6a157.firebaseapp.com',
    storageBucket: 'auth-6a157.firebasestorage.app',
  );
}
